### ISSUE TITLE
Services should stop in the reverse order

### ISSUE THREAD

**Issue by mcdonnelldean** [apparatus/fuge#37]
Generally when starting servers you put them in the other you want them to spin up. But generally when you want them to spin down it is preferable to go the opposite way. Thoughts on reversing spindown?

**Comment by AdrianRossouw** [comment]
i'd like to know which situations this matters in ?
i can see it being an issue when the mysql container goes away, but where else?

I think one of the weird edge cases around this could be because of our relationship to docker-compose, and afaik it does a dependency graph based on links between containers.
